Replace validation script with template-validation-action  (#85)
* fix azd up validation

* remove unready template

* use local backend for tf

* login az cli for some templates required

* iterate and validate all azure.yaml

* setup JAVA

* refactor creating issue action

* remove workaround

* only validate repo from Azure-Samples org

* use validation action

* revert template

* use latest validator

diff --git a/.github/workflows/regular-validate.yaml b/.github/workflows/regular-validate.yaml
--- a/.github/workflows/regular-validate.yaml
+++ b/.github/workflows/regular-validate.yaml
@@ -3,22 +3,16 @@ name: Regular Template Validation
 on:
   workflow_dispatch:
     inputs:
-      repository:
-        description: 'Repository for creating issues'
-        required: false
       create_issue:
-        description: 'Create issue if validation fails'
+        description: 'Create or update issue if validation fails'
         default: false
   schedule:
     - cron: '0 0 1 * *' # Runs at 00:00 UTC on the first day of every month
 
-permissions:
-  actions: read
-  contents: read
-  id-token: write
-
 jobs:
   setup:
+    permissions:
+      contents: read
     runs-on: ubuntu-latest
     outputs:
       repositories: ${{ steps.list-templates.outputs.repositories }}
@@ -32,13 +26,17 @@ jobs:
         id: list-templates
         working-directory: website/static
         run: |
-          repositories=`jq -r '.[] | .source' templates.json | jq -Rsc '[split("\n") | .[]| select(.!="")]'`
+          repositories=`jq -r '.[] | select(.source | contains("Azure-Samples")) | .source' templates.json | jq -Rsc '[split("\n") | .[]| select(.!="")]'`
           echo "repositories=$repositories" >> $GITHUB_OUTPUT
 
   validate-templates:
+    permissions:
+      contents: read
+      id-token: write
     if: ${{ needs.setup.outputs.repositories }}
     needs: setup
     runs-on: ubuntu-latest
+    timeout-minutes: 120
     strategy:
       fail-fast: false
       matrix:
@@ -46,6 +44,7 @@ jobs:
       max-parallel: 1
     name: ${{ matrix.repo }} 
     env:
+      CI: "true"
       # For azd login
       AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
       AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
@@ -54,41 +53,30 @@ jobs:
       AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
       ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
       ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
-      # OIDC token is not working for Terraform, so we need to use the client secret. Figure out a way to use OIDC token.
-      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-      # For Terraform backend
-      RS_CONTAINER_NAME: ${{ vars.RS_CONTAINER_NAME }}
-      RS_RESOURCE_GROUP: ${{ vars.RS_RESOURCE_GROUP }}
-      RS_STORAGE_ACCOUNT: ${{ vars.RS_STORAGE_ACCOUNT }}
+      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
+      # Use secret since terraform does not support federated token
+      ARM_CLIEND_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
       # template specific variables
       AZURE_DOCUMENTINTELLIGENCE_LOCATION: ${{ vars.AZURE_DOCUMENTINTELLIGENCE_LOCATION }}
       AZURE_OPENAI_LOCATION: ${{ vars.AZURE_OPENAI_LOCATION }}
-      MOCKED_OPENAI_API_KEY: ${{ vars.MOCKED_OPENAI_API_KEY }}
 
     steps:
-      - name: Install AZD
-        uses: Azure/setup-azd@v1.0.0
-
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           ref: ${{ github.ref }}
 
-      - name: Install python dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r .github/validator/requirements.txt
-
-      - name: Setup Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
-
       - name: Clone repo
         working-directory: ${{ runner.temp }}
         run: |
-          git clone ${{ matrix.repo }} template
-          candidate_hooks_paths=("./template/hooks" "./template/infra/hooks" "./template/scripts")
+          if [[ "${{ matrix.repo }}" == *"/tree/"* ]]; then
+            repo_url=$(echo "${{ matrix.repo }}" | sed 's|/tree/.*||')
+            branch_name=$(echo "${{ matrix.repo }}" | sed 's|.*tree/||')
+            git clone -b $branch_name $repo_url template
+          else
+            git clone ${{ matrix.repo }} template
+          fi
+          candidate_hooks_paths=("./template/hooks" "./template/infra/hooks" "./template/scripts" "./template/deploy/aca/scripts" "./template/deploy/aks/scripts" "./template/deploy/app-service/scripts")
 
           for hooks_path in "${candidate_hooks_paths[@]}"; do
             if [ -d "$hooks_path" ] && [ "$(ls -A $hooks_path/*.sh 2>/dev/null)" ]; then
@@ -99,37 +87,11 @@ jobs:
             fi
           done
 
-          if [ -f "./template/package.json" ]; then
-            echo "Installing npm dependencies"
-            cd template
-            npm install
-          fi
-
-      - name: Run Microsoft Security DevOps Analysis
-        uses: microsoft/security-devops-action@v1
-        id: msdo
-        env:
-          GDN_TEMPLATEANALYZER_ANALYZEDIRECTORY: ${{ runner.temp }}/template
-        with:
-          tools: templateanalyzer
-        continue-on-error: true
-      
       - name: Extract repo name
         id: extract_repo_name
         run: |
           repo_name=$(echo ${{ matrix.repo }} | sed -E 's|https://github.com/([^/]+/[^/]+).*|\1|')
-          repo_name_short=${repo_name##*/}
           echo "REPO_NAME=$repo_name" >> $GITHUB_OUTPUT
-          echo "REPO_NAME_SHORT=$repo_name_short" >> $GITHUB_OUTPUT
-
-      - name: Get repository topics
-        id: get_repo_topics
-        env:
-          GITHUB_TOKEN: ${{ secrets.AI_APP_BOT_TOKEN }}
-          REPO_NAME: ${{ steps.extract_repo_name.outputs.REPO_NAME }}
-        run: |
-          topics_list=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/${{ env.REPO_NAME }}/topics | jq -r '.names | join(",")')
-          echo "topics=\"$topics_list\"" >> $GITHUB_ENV
 
       - name: Set environment name with job id
         run: |
@@ -140,119 +102,73 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         continue-on-error: true
-      
-      - name: Log in with Azure (Federated Credentials)
-        if: ${{ env.AZURE_CLIENT_ID != '' }}
+
+      # TODO: Refine the logic to pick location based on scenario rather than repo name
+      - name: Pick available location for specific templates
+        id: pick_location
         run: |
-          azd auth login `
-            --client-id "$Env:AZURE_CLIENT_ID" `
-            --federated-credential-provider "github" `
-            --tenant-id "$Env:AZURE_TENANT_ID"
-        shell: pwsh
+          if [[ "${{ steps.extract_repo_name.outputs.REPO_NAME }}" == "Azure-Samples/agent-openai-python-prompty" ]]; then
+            echo "AZURE_LOCATION=${{ vars.AZURE_GPT4O_LOCATION }}" >> $GITHUB_ENV
+          elif [[ "${{ steps.extract_repo_name.outputs.REPO_NAME }}" == "Azure-Samples/assistant-data-openai-python-promptflow" ]]; then
+            echo "AZURE_LOCATION=${{ vars.AZURE_OPENAI_TURBO_LOCATION }}" >> $GITHUB_ENV
+          else
+            echo "AZURE_LOCATION=${{ vars.AZURE_LOCATION }}" >> $GITHUB_ENV
+          fi
       
-      - name: Run validation
-        working-directory: ${{ runner.temp }}/template
+      - name: Set customized environment variables
+        id: set_custom_env
         run: |
-          python ${{ github.workspace }}/.github/validator/validator.py . --azdup --azddown --output ../output.log --topics ${{ env.TOPICS }} --msdoresult ${{ steps.msdo.outputs.sarifFile }} --debug
+          if [[ "${{ steps.extract_repo_name.outputs.REPO_NAME }}" == "Azure-Samples/azure-search-openai-demo-java" || "${{ steps.extract_repo_name.outputs.REPO_NAME }}" == "Azure-Samples/azure-search-openai-demo-csharp" ]]; then
+            echo "MOCKED_OPENAI_API_KEY=sample-key" >> $GITHUB_ENV
+          fi
+
+      - id: validation
+        uses: microsoft/template-validation-action@main
+        with:
+          workingDirectory: ${{ runner.temp }}/template
         env:
-          AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
+          REPOSITORY_NAME: ${{ steps.extract_repo_name.outputs.REPO_NAME }}
           AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
           OPENAI_API_KEY: ${{ env.MOCKED_OPENAI_API_KEY }}
-          CREATE_ROLE_FOR_USER: false
           AZD_PREPDOCS_RAN: "false"
           SERVICE_API_RESOURCE_EXISTS: "false"
-          TOPICS: ${{ env.topics }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      
+      - id: check_result
+        run: |
+          if grep -q "FAILED" "${{ steps.validation.outputs.resultFile }}"; then
+            echo "RESULT=FAILED" >> $GITHUB_OUTPUT
+          else
+            echo "RESULT=PASSED" >> $GITHUB_OUTPUT
+          fi
 
       - name: Create or update issue if failed
-        if: github.event.inputs.create_issue == 'true'
-        working-directory: ${{ runner.temp }}
-        run: |
-          repo="${{ matrix.repo }}"
-          issue_number=$(gh issue list --author "ai-apps-bot" --repo "$repo" --json number | jq -r '.[0].number')
-          if grep -q "FAILED" output.log; then
-            echo "Validation failed, creating issue"
-            if [ "null" == $issue_number ]; then
-              gh issue create --title "[Auto] AI Gallery Standard Validation FAILED" --body-file output.log --repo $repo
-            else
-              gh issue edit $issue_number --body-file output.log --repo $repo
-            fi
-          else
-            echo "Validation passed, close opened issue"
-            if [ "null" != $issue_number ]; then
-              gh issue edit $issue_number --body-file output.log --repo $repo
-              gh issue close $issue_number --repo $repo --reason "Validation passed"
-            fi
-          fi
+        if: github.event.inputs.create_issue == 'true' && steps.check_result.outputs.RESULT == 'FAILED'
         env: 
           GITHUB_TOKEN: ${{ secrets.AI_APP_BOT_TOKEN }}
-
-      - name: Add repo name to output
         run: |
-          echo -e "\n# Repo: ${{ steps.extract_repo_name.outputs.REPO_NAME }}\n" >> ${{ runner.temp }}/output.md
-          cat ${{ runner.temp }}/output.log >> ${{ runner.temp }}/output.md
-
-      - name: Upload output artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ steps.extract_repo_name.outputs.REPO_NAME_SHORT }}
-          path: ${{ runner.temp }}/output.md
-
-  merge-result:
-    if: ${{ always() }}
-    needs:
-      - validate-templates
-      - setup
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download all artifacts
-        uses: actions/download-artifact@v4
-        with:
-          path: merged-results
-
-      - name: Summarize
-        working-directory: merged-results
-        run: |
-          total=0
-          failed=0
-          failed_repos=""
-          for file in $(ls */output.md); do
-            total=$((total + 1))
-            if grep -q "FAILED" "$file"; then
-              failed=$((failed + 1))
-              folder=$(dirname "$file")
-              failed_repos="${failed_repos}\n${folder}"
-            fi
-          done
-          echo -e "# Validation Summary\n"
-          echo -e "Failed/Total: $failed/$total\nFailed Repos:${failed_repos}\n" >> summary.md
-          cat ./*/output.md >> summary.md
-
-      - name: Find existing issue
-        if: github.event.inputs.create_issue == 'true'
-        id: find-existing-issue
-        run: |
-          repo="${{ github.event.inputs.repository || github.repository }}"
-          issue_number=$(gh issue list --author "ai-apps-bot" --repo "$repo" --json number | jq -r '.[0].number')
-          echo "issue_number=$issue_number" >> $GITHUB_OUTPUT
-        env:
-          GITHUB_TOKEN: ${{ secrets.AI_APP_BOT_TOKEN }}
-
-      - name: Create or update summary issue
-        if: github.event.inputs.create_issue == 'true'
-        working-directory: merged-results
-        run: |
-          repo="${{ github.event.inputs.repository || github.repository }}"
-          issue_number="${{ steps.find-existing-issue.outputs.issue_number }}"
+          echo "Validation failed, creating issue"
+          repo="${{ steps.extract_repo_name.outputs.REPO_NAME }}"
+          issue_number=$(gh issue list --author "ai-apps-bot" --repo "$repo" --state "all" --json number | jq -r '.[0].number')
           if [ "null" == $issue_number ]; then
-            gh issue create --title "Templates Validation Summary" --body-file summary.md --repo $repo
+            gh issue create --title "[Auto] AI Gallery Standard Validation FAILED" --body-file "${{ steps.validation.outputs.resultFile }}" --repo $repo
           else
-            gh issue edit $issue_number --body-file summary.md --repo $repo
+            gh issue edit $issue_number --body-file "${{ steps.validation.outputs.resultFile }}" --repo $repo
           fi
-        env:
-          GITHUB_TOKEN: ${{ secrets.AI_APP_BOT_TOKEN }}
 
-      - name: Upload merged results
-        uses: actions/upload-artifact@v4
-        with:
-          name: 0.merged-results
-          path: merged-results/summary.md
+      - name: Close issue if passed
+        if: github.event.inputs.create_issue == 'true' && steps.check_result.outputs.RESULT == 'PASSED'
+        env: 
+          GITHUB_TOKEN: ${{ secrets.AI_APP_BOT_TOKEN }}
+        run: |
+          echo "Validation passed, close opened issue"
+          repo="${{ steps.extract_repo_name.outputs.REPO_NAME }}"
+          issue_number=$(gh issue list --author "ai-apps-bot" --repo "$repo" --json number | jq -r '.[0].number')
+          if [ "null" != $issue_number ]; then
+            gh issue edit $issue_number --body-file "${{ steps.validation.outputs.resultFile }}" --repo $repo
+            gh issue close $issue_number --repo $repo --reason "Validation passed"
+          fi
+      
+      - name: Exit with failure if validation failed
+        if: steps.check_result.outputs.RESULT == 'FAILED'
+        run: exit 1
